# -*- coding: utf-8 -*-
"""Single source of truth for Xu Zhang's publication list (excluding the LLM patent-classification paper)."""
import json, os
_raw = json.load(open(os.path.join(os.path.dirname(__file__), "_abstracts_raw.json")))
def _abs(doi): return _raw[doi]["abstract"]

AUTHOR = {
    "name": "Xu Zhang",
    "orcid": "https://orcid.org/0000-0002-4143-0715",
    "scholar": "https://scholar.google.com/citations?user=MnZDgiUAAAAJ",
    "github": "https://github.com/CodeZx6",
    "openalex": "https://openalex.org/A5040099809",
    "semanticscholar": "https://www.semanticscholar.org/author/2260823473",
    "email": "xu.zhang12@hdr.mq.edu.au",
    "affiliation": "School of Computing, Macquarie University",
    "affiliation_url": "https://www.mq.edu.au/",
    "site": "https://codezx6.github.io",
}

PAPERS = [
 dict(
  key="zhang2026duet", slug="duet",
  short="DUET",
  title="DUET: Unified Dual-Space Emotion Control for Diffusion and Flow-Matching Driven Text-to-Speech",
  authors=["Xu Zhang","Longbing Cao","Zhangkai Wu"],
  venue="arXiv preprint", venue_type="preprint", year=2026, date="2026-05-20",
  arxiv="2606.00066",
  links={"Demo":"https://codezx6.github.io/duet-demo-fresh/"},
  keywords=["emotional text-to-speech","emotion control","diffusion TTS","flow-matching TTS","activation steering","classifier guidance","plug-and-play","humanoid robot","Ameca"],
  tldr="DUET adds fine-grained, plug-and-play emotion control to pretrained diffusion and flow-matching TTS models by steering a linearly decodable emotion direction in hidden space and guiding the mel output through a differentiable vocoder, with no retraining.",
  findings=[
   "Emotion is a linearly decodable direction in the frozen hidden states of diffusion and flow-matching TTS models, and it is nearly orthogonal to the speaker-identity direction.",
   "DUET unifies hidden-space steering and mel-space guidance in a single per-step update during sampling, so any pretrained backbone gains emotion control without fine-tuning.",
   "Evaluated on five architecturally different pretrained TTS backbones and three datasets, DUET outperforms 10 supervised emotional-TTS baselines and receives the highest human-rated emotion appropriateness.",
   "Deployed on an Ameca humanoid robot to produce expressive emotional speech for embodied interaction.",
  ],
  abstract="Diffusion and flow-matching based text-to-speech (TTS) models excel in naturalness but often lack explicit emotion control, as emotional signals remain entangled with speaker identity. We discover that emotion embedding emerges as a linearly decodable direction of frozen hidden states, nearly orthogonal to the direction embedding speaker identity. This inspires a plug-and-play framework DUET for emotion control over pretrained diffusion and flow-matching based TTS models. During generation, DUET unifies dual-space control to achieve fine-grained emotion intervention in a single per-step update: hidden space steering shifts generation along the target emotion direction, while mel-space guidance refines spectral details through gradients backpropagated from a differentiable vocoder. We validate DUET on five architecturally diverse pretrained TTS backbones across three datasets, where it outperforms 10 supervised state-of-the-art emotional TTS baselines across paradigms and achieves the highest human-rated emotion appropriateness. To further showcase its qualitative behavior, we deploy DUET on an Ameca humanoid robot, where it produces richly expressive emotional speech on the humanoid, demonstrating the strong potential for plug-and-play affective interaction for embodied agents.",
 ),
 dict(
  key="zhang2026physioser", slug="physioser",
  short="PhysioSER",
  title="Learning Physiology-Informed Vocal Spectrotemporal Representations for Speech Emotion Recognition",
  authors=["Xu Zhang","Longbing Cao","Runze Yang","Zhangkai Wu"],
  venue="arXiv preprint", venue_type="preprint", year=2026, date="2026-02-03",
  arxiv="2602.13259", note="13 pages, 5 figures",
  keywords=["speech emotion recognition","physiology-informed","quaternion convolution","amplitude and phase","self-supervised speech models","interpretable SER","humanoid robot"],
  tldr="PhysioSER couples vocal amplitude and phase through voice anatomy and physiology (VAP) informed quaternion representations, aligned with a frozen self-supervised backbone, giving an interpretable and efficient plug-and-play speech emotion recognizer validated on 14 datasets and 10 languages.",
  findings=[
   "Most deep SER models use amplitude only; PhysioSER builds amplitude and phase views grounded in vocal-tract and glottal-source physiology and models their interaction with Hamilton-structured quaternion convolutions.",
   "A Contrastive Projection and Alignment framework aligns the physiology branch with a frozen SSL backbone, followed by a shallow attention fusion head.",
   "Evaluated across 14 datasets, 10 languages, and 6 SSL backbones, and deployed in real time on a humanoid robotic platform.",
  ],
  abstract="Speech emotion recognition (SER) is essential for humanoid robot tasks such as social robotic interactions and robotic psychological diagnosis, where interpretable and efficient models are critical for safety and performance. Existing deep models trained on large datasets remain largely uninterpretable, often insufficiently modeling underlying emotional acoustic signals and failing to capture and analyze the core physiology of emotional vocal behaviors. Physiological research on human voices shows that the dynamics of vocal amplitude and phase correlate with emotions through the vocal tract filter and the glottal source. However, most existing deep models solely involve amplitude but fail to couple the physiological features of and between amplitude and phase. Here, we propose PhysioSER, a physiology-informed vocal spectrotemporal representation learning method, to address these issues with a compact, plug-and-play design. PhysioSER constructs amplitude and phase views informed by voice anatomy and physiology (VAP) to complement SSL models for SER. This VAP-informed framework incorporates two parallel workflows: a vocal feature representation branch to decompose vocal signals based on VAP, embed them into a quaternion field, and use Hamilton-structured quaternion convolutions for modeling their dynamic interactions; and a latent representation branch based on a frozen SSL backbone. Then, utterance-level features from both workflows are aligned by a Contrastive Projection and Alignment framework, followed by a shallow attention fusion head for SER classification. PhysioSER is shown to be interpretable and efficient for SER through extensive evaluations across 14 datasets, 10 languages, and 6 backbones, and its practical efficacy is validated by real-time deployment on a humanoid robotic platform.",
 ),
 dict(
  key="gong2026dstcn", slug="dstcn",
  short="DSTCN",
  title="Exploiting dynamic spatio-temporal correlations for origin-destination demand prediction",
  authors=["Yongshun Gong","Piao Yu","Xu Zhang","Xinxin Zhang","Xiushan Nie","Haoliang Sun"],
  venue="Expert Systems with Applications", venue_type="journal", year=2026, date="2025-10-25",
  volume="299", pages="130095", doi="10.1016/j.eswa.2025.130095", issn="0957-4174",
  oa="hybrid (CC BY)", oa_url="https://doi.org/10.1016/j.eswa.2025.130095",
  code="https://github.com/CodeZx6/DSTCN",
  keywords=["origin-destination demand prediction","metro OD matrix","spatio-temporal correlation","graph convolution","attention","intelligent transportation"],
  tldr="DSTCN (Dynamic Spatio-Temporal Correlation Network) forecasts origin-destination demand with three modules: Glstm2D for bidirectional origin/destination demand trends, Simformer for Transformer-based inter-regional similarity over the OD matrix, and FF-TM for temporal fusion; it beats state-of-the-art baselines on NYC-TOD2018, NYC-TOD2019, and HZMetro.",
  findings=[
   "Glstm2D jointly learns demand evolution from both the origin and the destination perspective.",
   "Simformer dynamically extracts and integrates inter-regional correlations across the OD matrix with a Transformer.",
   "FF-TM combines multi-source spatio-temporal features for next-step prediction.",
   "Evaluated on three large-scale real-world datasets (NYC-TOD2018, NYC-TOD2019, HZMetro); published open access (CC BY) in Expert Systems with Applications, vol. 299 (2026), online October 2025.",
  ],
  abstract=_abs("10.1016/j.eswa.2025.130095"),
 ),
 dict(
  key="cao2025mutual", slug="mutual-enhancement-hsi",
  short="Mutually Enhancement Network",
  title="A Mutually Enhancement Network for Superpixel Segmentation and Classification of Hyperspectral Image",
  authors=["Mengxin Cao","Yongmin Li","Xu Zhang","Guixin Zhao","Guohua Lv","Aimei Dong","Jinyong Cheng","Wei Li","Xiangjun Dong"],
  venue="IEEE Transactions on Geoscience and Remote Sensing", venue_type="journal", year=2025, date="2025-09-10",
  volume="63", pages="1-14", doi="10.1109/TGRS.2025.3608942", issn="1558-0644", oa="closed",
  keywords=["hyperspectral image classification","superpixel segmentation","mutual enhancement","remote sensing","deep learning"],
  tldr="A network in which superpixel segmentation and hyperspectral classification reinforce each other, so segmentation boundaries and class predictions improve jointly.",
  findings=[
   "Treats superpixel segmentation and pixel classification as mutually enhancing tasks rather than a fixed preprocessing pipeline.",
   "Published in IEEE TGRS, volume 63 (2025).",
  ],
  abstract=_abs("10.1109/tgrs.2025.3608942"),
 ),
 dict(
  key="zhang2025mrufp", slug="mr-ufp",
  short="MR-UFP",
  title="Enhancing urban flow prediction via mutual reinforcement with multi-scale regional information",
  authors=["Xu Zhang","Mengxin Cao","Yongshun Gong","Xiaoming Wu","Xiangjun Dong","Ying Guo","Long Zhao","Chengqi Zhang"],
  venue="Neural Networks", venue_type="journal", year=2025, date="2024-11-16",
  volume="182", pages="106900", doi="10.1016/j.neunet.2024.106900", issn="0893-6080", pmid="39579750", oa="closed",
  code="https://github.com/CodeZx6/MR-UPF",
  keywords=["urban flow prediction","spatial-temporal heterogeneity","contrastive pre-training","random masking","multi-scale region classification","multi-task learning","intelligent transportation systems"],
  tldr="MR-UFP improves urban flow prediction on small or noisy data by pre-training with spatial-temporal masking and contrastive learning, then jointly training the predictor with a multi-scale region-classification task that mutually reinforces spatial features.",
  findings=[
   "Spatial-temporal random masking plus contrastive pre-training mines heterogeneity directly from historical flows.",
   "Spatial feature extraction is reformulated as a mutual-reinforcement task with a multi-scale regional classification auxiliary task, with adaptive environment fusion and real-time graph processing.",
   "A joint loss balances the two tasks; experiments on two real-world datasets show gains over baselines even with minimal data.",
  ],
  abstract="Intelligent Transportation Systems (ITS) are essential for modern urban development, with urban flow prediction being a key component. Accurate flow prediction optimizes routes and resource allocation, benefiting residents, businesses, and the environment. However, few methods address the spatial-temporal heterogeneity of urban flows. Existing methods typically capture spatial features solely from urban flows, but spatial feature sensitivity becomes a bottleneck when dealing with small or noisy datasets. To address this issue, we propose a method for urban flow prediction via mutual reinforcement with multi-scale regional information (MR-UFP). Firstly, we employ spatial-temporal random masking and spatial-temporal contrastive learning pre-training to directly mine spatial-temporal heterogeneity from historical flow data. Secondly, we transform the task of spatial feature extraction and embedding for urban flow prediction into a mutual reinforcement task by multi-scale region classification auxiliary task. The adaptive environment fusion module and real-time graph processing dynamically correlate regional and environmental features during flow prediction. To balance the mutual reinforcement of the two tasks, we design a joint loss function to optimize feature embedding and feedback correction, ensuring robust and accurate urban flow prediction. Extensive experiments on two real-world datasets demonstrate that MR-UFP outperforms baseline models, showcasing its robustness and effectiveness even with minimal data.",
 ),
 dict(
  key="yu2025bistif", slug="bist-if",
  short="BiST-IF",
  title="Enhancing origin–destination flow prediction via bi-directional spatio-temporal inference and interconnected feature evolution",
  authors=["Piao Yu","Xu Zhang","Yongshun Gong","Jian Zhang","Haoliang Sun","Junjie Zhang","Xinxin Zhang","Yilong Yin"],
  venue="Expert Systems with Applications", venue_type="journal", year=2025, date="2024-11-22",
  volume="264", pages="125679", doi="10.1016/j.eswa.2024.125679", issn="0957-4174", oa="closed",
  code="https://github.com/CodeZx6/BiST-IF",
  keywords=["origin-destination flow prediction","OD delay correction","bi-directional attention","mutual information","Out-OD flow","HZMetro","NYC taxi","intelligent transportation"],
  tldr="BiST-IF predicts metro and taxi origin-destination flows by correcting delayed OD matrices, applying bi-directional origin/destination attention, and letting OD and arrival (Out-OD) flows evolve jointly through mutual-information attention.",
  findings=[
   "OD Delay Correction estimates delayed OD distributions from periodic patterns and recent Out-OD flows.",
   "OD Bi-directional Attention extracts trends with BiLSTM and origin-wise plus destination-wise attention.",
   "Mutual Information Flow Evolution fuses OD and Out-OD features with multi-head attention and gated updates.",
   "Evaluated on HZMetro (80 stations, 10-minute intervals) and NYC-TOD2018 (69 Manhattan taxi zones, 30-minute intervals).",
  ],
  abstract="Origin–destination (OD) flow prediction is crucial for predicting inter-station passenger flows in intelligent transport systems. However, previous OD prediction methods have ignored the delay of OD flows and failed to focus on the supplementary effect of the arrival OD flow (Out-OD) flow data on OD flows. We innovatively propose an OD flow prediction method based on Bidirectional Attention and Interconnected Feature Evolution (BiST-IF) to address these challenges. Firstly, we propose a correction method based on period delay probability and real-time flow features for OD flow information. Furthermore, for the flow information of different periods, we design a bi-directional attention module to achieve the preliminary prediction by deconstructing and analyzing the temporal and flow features of OD flow and fusing the temporal and spatial features. After that, we design the mutual information module of Out-OD and OD flows to model their interconnected feature evolution.",
  abstract_note="Abstract shown up to the publicly indexed portion; see the publisher page for the full text.",
 ),
 dict(
  key="yao2024leaf", slug="leaf-disease-attention",
  short="Leaf disease recognition",
  title="Automatic visual recognition for leaf disease based on enhanced attention mechanism",
  authors=["Yumeng Yao","Xiaodun Deng","Xu Zhang","Junming Li","Wenxuan Sun","Gechao Zhang"],
  venue="PeerJ Computer Science", venue_type="journal", year=2024, date="2024-11-04",
  volume="10", pages="e2365", doi="10.7717/peerj-cs.2365", issn="2376-5992", pmid="39650513", pmcid="PMC11623051",
  oa="gold (CC BY)", oa_url="https://doi.org/10.7717/peerj-cs.2365", pdf="https://peerj.com/articles/cs-2365.pdf",
  keywords=["plant leaf disease recognition","tomato disease","attention mechanism","computer vision","smart agriculture"],
  tldr="An enhanced-attention vision model for fast and accurate recognition of tomato leaf diseases, aimed at early disease prevention in agriculture.",
  findings=[
   "Open access (CC BY) in PeerJ Computer Science, also indexed in PubMed Central.",
  ],
  abstract=_abs("10.7717/peerj-cs.2365"),
 ),
 dict(
  key="cao2024s3fsl", slug="spatial-spectral-semantic-fsl",
  short="Spatial-Spectral-Semantic FSL",
  title="Spatial-Spectral–Semantic Cross-Domain Few-Shot Learning for Hyperspectral Image Classification",
  authors=["Mengxin Cao","Xu Zhang","Jinyong Cheng","Guixin Zhao","Wei Li","Xiangjun Dong"],
  venue="IEEE Transactions on Geoscience and Remote Sensing", venue_type="journal", year=2024, date="2024-07-25",
  volume="62", pages="1-15", doi="10.1109/TGRS.2024.3434484", issn="1558-0644", oa="closed",
  keywords=["hyperspectral image classification","few-shot learning","cross-domain","spatial-spectral","semantic","remote sensing"],
  tldr="A cross-domain few-shot learner for hyperspectral images that jointly exploits spatial, spectral, and semantic information to classify new scenes from very few labelled samples.",
  findings=["Published in IEEE TGRS, volume 62 (2024), pages 1-15."],
  abstract=_abs("10.1109/tgrs.2024.3434484"),
 ),
 dict(
  key="zhang2023stcsl", slug="st-csl",
  short="ST-CSL",
  title="Spatio-temporal fusion and contrastive learning for urban flow prediction",
  authors=["Xu Zhang","Yongshun Gong","Chengqi Zhang","Xiaoming Wu","Ying Guo","Wenpeng Lu","Long Zhao","Xiangjun Dong"],
  venue="Knowledge-Based Systems", venue_type="journal", year=2023, date="2023-10-21",
  volume="282", pages="111104", doi="10.1016/j.knosys.2023.111104", issn="0950-7051", oa="closed",
  code="https://github.com/CodeZx6/ST-CSL",
  keywords=["urban flow prediction","contrastive learning","spatio-temporal fusion","periodicity","functional regions","traffic prediction"],
  tldr="ST-CSL fuses temporal-view and spatial-view contrastive learning so an urban flow predictor captures global periodicity and the hidden flow relationships between functionally similar regions.",
  findings=[
   "Temporal-view extraction captures the distribution and change of global urban-flow periodicity.",
   "Spatial-view extraction captures implied flow variation between similar regions.",
   "Separate closeness, period, and trend encoders are fused by a residual fusion network.",
  ],
  abstract="Urban flow prediction is critical for urban planning, management, and safety. However, owing to the inherent instability of urban flows, prediction accuracy requires the fusion of multi-view influencing factors. Current prediction methods are insensitive to periodic changes in urban flows, and rarely consider the implied spatial and temporal correlations between similar functional areas. Thus, we propose a method based on spatiotemporal fusion and contrastive learning. We construct an extraction module of spatial and temporal views based on contrastive learning in the spatial and temporal dimensions. With the temporal view extraction, we can obtain the distribution and change in the global urban flow periodicity. Using the spatial view extraction, we can obtain the implied flow variation relationship between similar regions.",
  abstract_note="Abstract shown up to the publicly indexed portion; see the publisher page for the full text.",
 ),
 dict(
  key="zhang2023mcstl", slug="mcstl",
  short="MCSTL",
  title="Mask- and Contrast-Enhanced Spatio-Temporal Learning for Urban Flow Prediction",
  authors=["Xu Zhang","Yongshun Gong","Xinxin Zhang","Xiaoming Wu","Chengqi Zhang","Xiangjun Dong"],
  venue="Proceedings of the 32nd ACM International Conference on Information and Knowledge Management (CIKM '23)", venue_short="CIKM 2023",
  venue_type="conference", year=2023, date="2023-10-21",
  pages="3298-3307", doi="10.1145/3583780.3614958", publisher="ACM",
  oa="gold", oa_url="https://dl.acm.org/doi/pdf/10.1145/3583780.3614958", pdf="https://dl.acm.org/doi/pdf/10.1145/3583780.3614958",
  code="https://github.com/CodeZx6/MCSTL",
  keywords=["urban flow prediction","masked pre-training","contrastive learning","graph attention","spatio-temporal learning","CIKM"],
  tldr="MCSTL pre-trains an urban flow model with a mask-reconstruction task across space and time and a graph-based contrastive task that weights regions by inter-regional attention, then fine-tunes for flow prediction.",
  findings=[
   "A mask-enhanced pre-training task learns latent correlations across spatial and temporal dimensions.",
   "A graph-based method uses inter-regional attention weights to derive contrastive correlations between regions.",
   "Published open access in the ACM Digital Library (CIKM 2023, pages 3298-3307).",
  ],
  abstract=_abs("10.1145/3583780.3614958"),
 ),
 dict(
  key="dang2026urmdet", slug="urmdet-simfire",
  short="URMDet-SimFire",
  title="URMDet-SimFire: Trustworthy multimodal detection with uncertainty and reliability modeling for fire and smoke analytics",
  authors=["Zhonghua Dang","Xu Zhang"],
  venue="Array", venue_type="journal", year=2026, date="2026-09-01",
  volume="31", pages="101124", doi="10.1016/j.array.2026.101124", issn="2590-0056",
  oa="open access (CC BY)", oa_url="https://doi.org/10.1016/j.array.2026.101124",
  keywords=["fire detection","smoke detection","multimodal detection","uncertainty modeling","reliability","trustworthy AI"],
  tldr="A trustworthy multimodal fire-and-smoke detector that models uncertainty and reliability of each modality.",
  findings=["Listed on ORCID 0000-0002-4143-0715 but not yet on Google Scholar; add it to the Scholar profile."],
  abstract=None,
 ),
]

from enrich import E
for _p in PAPERS:
    _p.update(E[_p["key"]])
